name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: testtt
      id: testtt
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testtt
        setup-command: npm install
        command: npm test
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTTT_RESULTS: "${{steps.testtt.outputs.result}}"
      with:
        runners: testtt
